<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>test_ros2trace</name>
  <version>8.0.0</version>
  <description>Tests for the ros2trace package.</description>
  <maintainer email="bedard.christophe@gmail.com">Christophe Bedard</maintainer>
  <license>Apache 2.0</license>
  <url type="website">https://github.com/ros2/ros2_tracing</url>
  <url type="repository">https://github.com/ros2/ros2_tracing</url>
  <url type="bugtracker">https://github.com/ros2/ros2_tracing/issues</url>
  <author email="bedard.christophe@gmail.com">Christophe Bedard</author>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_mypy</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>ament_xmllint</test_depend>
  <test_depend>launch</test_depend>
  <test_depend>launch_ros</test_depend>
  <test_depend>lttngpy</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>ros2run</test_depend>
  <test_depend>ros2trace</test_depend>
  <test_depend>test_tracetools</test_depend>
  <test_depend>tracetools</test_depend>
  <test_depend>tracetools_read</test_depend>
  <test_depend>tracetools_test</test_depend>
  <test_depend>tracetools_trace</test_depend>

  <!-- TODO(clalancette): This is actually a false dependency,
	  but we add it here to ensure that we don't run multiple
	  tracing tests in parallel, which often ends up crashing.
  -->
  <test_depend>test_tracetools_launch</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
